from typing import Protocol

from src.core.value_objects import Card


class ICardService(Protocol):
    async def add_card(self, data: Card) -> None: ...
    async def delete_card(self, data: Card) -> None: ...


class MochiCardService:
    async def add_card(self, data: Card) -> None: ...
    async def delete_card(self, data: Card) -> None: ...


class AnkiCardService:
    async def add_card(self, data: Card) -> None: ...
    async def delete_card(self, data: Card) -> None: ...
